---
- name: create a webserver
  hosts: all
  tasks:
    - name: install httpd server
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: enable http
      firewalld:
        service: http
        state: enabled
        permanent: True
        immediate: True

    - name: start the service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: True

    - name: create index.html
      ansible.builtin.copy:
        content: "<h1> Hello </h1>"
        dest: "/var/www/html/index.html"

...